services:
  servilog:
    image: ghcr.io/jorges15/servilog:latest
    container_name: servilog
    restart: unless-stopped
    volumes:
      - ./data:/data
    networks:
      - caddy_net

networks:
  caddy_net:
    external: true
